name       : perl-test-requires
version    : 0.10
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/T/TO/TOKUHIROM/Test-Requires-0.10.tar.gz : 2768a391d50ab94b95cefe540b9232d7046c13ee86d01859e04c044903222eb5
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Requires - Checks to see if the module can be loaded
description: |
    Test::Requires checks to see if the module can be loaded.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
